version: '3.8'

services:

  my_rust_app:

    build:
      context: ../tp-wik-dps-tp01
      dockerfile: Dockerfile

    expose:
      - '7878'

    deploy:
      replicas: 4
    
    restart: always
    
    networks:
      - default-network

  proxy:

      image: nginx:latest

      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
      ports:
        - 8080:8080

      depends_on: 
        - my_rust_app
      
      networks:
        - default-network

networks:
  default-network:
    driver: bridge