version: '3.8'

services:

  wordpress:
    image: wordpress

    volumes:
      - wp_data:/var/www/html

    deploy:
      replicas: 3

    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WPFPM_WP_REDIS_HOST=redis
      - WPFPM_WP_REDIS_PORT=6379
      - WP_PLUGINS="redis-cache"
    
    restart: always
    
    networks:
      - default-network

  mariadb:
    image: mariadb

    command: '--default-authentication-plugin=mysql_native_password'

    volumes:
      - db_data:/var/lib/mysql

    environment:
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

    expose:
      - 3306
      - 33060

    restart: always

    networks:
      - default-network

  redis:
    image: redis

    expose:
      - '6379'

    restart: always

    networks:
      - default-network

  proxy:

      image: nginx:latest

      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
      ports:
        - 8080:8080

      depends_on: 
        - wordpress
      
      networks:
        - default-network

networks:
  default-network:
    driver: bridge

volumes:
  db_data:
  wp_data: